language: node_js
node_js:
- 12

script:
- echo "run test script here"

cache:
- yarn

# after_success:

notifications:
  email:
    recipients:
    - namvhoang02@gmail.com
    on_success: never
    on_failure: always

git:
  depth: 1

deploy:
  provider: npm
  email: namvhoang02@gmail.com
  edge: true
  api_token:
    secure: kXSIGyRjrXoog4vECjF89YgPQ0qpmKmeiMfFBTur/jSAUYm9AMW51kTTdm6yEA4KAvXUyjD7qhWJKmqSLl53unqexjfm9OiasE3ZC2n8uHEBW0gReHpqZ5g78wqHd+YX8VpJbWN241/1cgbjGSa2koReU/ZcxKhAL7HTm7eFmK7o40WTPSVWQ1aDXL59UWPylVPVEXf9R3xHiio3ymh+XzQbe0kRZ8inax+R8vAfz1qLUk5x/mK6xwPVp5Vos/fRrZqjN62cyrFjuB0yfqX41u9CtG7aYfeNKS6sEeBN323ncOOn/MfzijAIP74tgo8v7ps4gSjPYOfWQAgd+zPT7o4g21KrJRc2hkwcDcbk6jxOxY1N7f5/FE7WaMYt7HCJsMNYnS8Tv0LG9dZjh3VZ5p5ZPyKHDoTWOCoh+BnikTaxs5/ZilRSGEaqfAQ8OULmjKelqNl2RS07Ry6HW6wC0REhYafRSbSH6emP6sPljthC8JjPUpdSN37XwSPa+FJyvNIe5ZtXw02qvRI2H7vRxXejZRBlXpmda4muimHbp9cvrc0tY3kSwHaVEOBdmGri0/QmG56tLSjNHzkUcO+2UXv4gf3xX9UxxoN4g+PwzBAWbnz+HFzauXs+XHAKVbARchG/lQ+LgiZKcT+yHQYHOmUJhbV3+NQWT3yT5dbksIA=
  on:
    tags: true
    repo: namvhoang02/penguin-scroll
